/// <reference types="react" />
export declare const Hair: {
    Afro: () => JSX.Element;
    Bald: () => JSX.Element;
    BaldSides: () => JSX.Element;
    BaldTop: () => JSX.Element;
    Bangs: () => JSX.Element;
    BangsFilled: () => JSX.Element;
    Bear: () => JSX.Element;
    Bun: () => JSX.Element;
    BunCurly: () => JSX.Element;
    Buns: () => JSX.Element;
    FlatTop: () => JSX.Element;
    FlatTopLong: () => JSX.Element;
    HatHip: () => JSX.Element;
    Long: () => JSX.Element;
    LongAfro: () => JSX.Element;
    LongBangs: () => JSX.Element;
    LongCurly: () => JSX.Element;
    Medium: () => JSX.Element;
    MediumBangs: () => JSX.Element;
    MediumBangsFilled: () => JSX.Element;
    MediumLong: () => JSX.Element;
    MediumShort: () => JSX.Element;
    MediumStraight: () => JSX.Element;
    Mohawk: () => JSX.Element;
    MohawkDino: () => JSX.Element;
    Pomp: () => JSX.Element;
    ShavedRight: () => JSX.Element;
    ShavedSides: () => JSX.Element;
    ShavedWavy: () => JSX.Element;
    Short: () => JSX.Element;
    ShortCurly: () => JSX.Element;
    ShortMessy: () => JSX.Element;
    ShortScratch: () => JSX.Element;
    ShortVolumed: () => JSX.Element;
    ShortWavy: () => JSX.Element;
};
export interface HairType {
    Afro: React.ElementType;
    Bald: React.ElementType;
    BaldSides: React.ElementType;
    BaldTop: React.ElementType;
    Bangs: React.ElementType;
    BangsFilled: React.ElementType;
    Bear: React.ElementType;
    Bun: React.ElementType;
    BunCurly: React.ElementType;
    Buns: React.ElementType;
    FlatTop: React.ElementType;
    FlatTopLong: React.ElementType;
    HatHip: React.ElementType;
    Long: React.ElementType;
    LongAfro: React.ElementType;
    LongBangs: React.ElementType;
    LongCurly: React.ElementType;
    Medium: React.ElementType;
    MediumBangs: React.ElementType;
    MediumBangsFilled: React.ElementType;
    MediumLong: React.ElementType;
    MediumShort: React.ElementType;
    MediumStraight: React.ElementType;
    Mohawk: React.ElementType;
    MohawkDino: React.ElementType;
    Pomp: React.ElementType;
    ShavedRight: React.ElementType;
    ShavedSides: React.ElementType;
    ShavedWavy: React.ElementType;
    Short: React.ElementType;
    ShortCurly: React.ElementType;
    ShortMessy: React.ElementType;
    ShortScratch: React.ElementType;
    ShortVolumed: React.ElementType;
    ShortWav: React.ElementType;
}
